#!/usr/bin/env python3
"""
Example: Generate an HWPX document from structured data
(No COM/Hancom Office required)

Usage:
    python generate_report.py output.hwpx
"""
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from hwpx_toolkit.generator import HWPXGenerator


def main():
    output_path = sys.argv[1] if len(sys.argv) > 1 else "output.hwpx"

    template_dir = os.environ.get("HWPX_TEMPLATE_DIR")
    if not template_dir:
        print("Note: HWPX_TEMPLATE_DIR not set. Using minimal built-in template.")
        print("      For better results, set HWPX_TEMPLATE_DIR to a directory")
        print("      containing a valid HWPX template file.")

    gen = HWPXGenerator(template_dir=template_dir)

    # Build document paragraphs
    paragraphs = [
        ("title1", "Sample Report"),
        ("title2", "Generated by hwpx-toolkit"),
        ("blank", ""),
        ("body",   f"Date: {__import__('datetime').date.today()}"),
        ("blank", ""),
        ("title2", "1. Introduction"),
        ("body",   "This document was generated programmatically using hwpx-toolkit."),
        ("body",   "HWP/HWPX is the dominant document format in South Korea."),
        ("blank", ""),
        ("title2", "2. Features"),
        ("bullet", "Text and table extraction from HWP/HWPX"),
        ("bullet", "Document creation and editing via COM bridge"),
        ("bullet", "Vectorization for RAG pipelines"),
        ("bullet", "Template-based generation (no Office required)"),
        ("bullet", "MCP server for AI assistant integration"),
        ("blank", ""),
        ("title2", "3. Conclusion"),
        ("body",   "hwpx-toolkit bridges Korean document formats with modern AI tooling."),
    ]

    output = gen.generate(paragraphs, output_path=output_path)
    print(f"✅ Generated: {output}")


if __name__ == "__main__":
    main()
